# eureka service服务端口
server:
  port: 8763
spring:
  application:
    name: cloud-eureka-server  # 应用名称, 应用名称会在Eureka中作为服务名称

# eureka客户端配置
eureka:
  client:
    service-url:
      # 集群模式下。应该指向其他server
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka  # 客户端与服务端交互的地址（单机server指向自己）
      defaultZone: http://127.0.0.1:8761/eureka, http://127.0.0.1:8762/eureka, http://127.0.0.1:8763/eureka
    register-with-eureka: true # 当前自己就是server，不需要注册自己
    fetch-registry: true # 是否从注册中心获取的服务信息，自己是server不需要
  instance:
    hostname: localhost # 当前Eureka server的主机名